# Generated by Django 4.0.4 on 2022-06-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.AddField(
            model_name='note',
            name='model_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Изображение'),
        ),
    ]
