# Generated by Django 4.0.4 on 2022-06-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_note_image_note_model_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
