# Generated by Django 4.0.4 on 2022-06-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
    ]
